# Generated by Django 5.0.4 on 2024-04-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='previous_uuid',
            new_name='next_version_uuid',
        ),
    ]
