# Generated by Django 5.0.4 on 2024-04-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='next_version_uuid',
            new_name='previous_version_uuid',
        ),
    ]
