# Generated by Django 5.0.4 on 2024-04-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_rename_next_version_uuid_banner_previous_version_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banners.feature'),
        ),
    ]
