# Generated by Django 5.0.4 on 2024-04-09 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_alter_banner_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedView',
            fields=[
                ('uuid', models.UUIDField(db_column='uuid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='id')),
                ('feature', models.IntegerField(db_column='feature_id')),
                ('tag_id', models.IntegerField(db_column='tag_id')),
                ('content', models.JSONField(blank=True, db_column='content', null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='is_active', default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('previous_version_uuid', models.UUIDField(blank=True, db_column='previous_version_uuid', null=True)),
            ],
            options={
                'db_table': 'banners',
                'managed': False,
            },
        ),
    ]
