# Generated by Django 5.0.4 on 2024-04-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_materializedview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedViewBanners',
            fields=[
                ('uuid', models.UUIDField(db_column='uuid', primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='id')),
                ('content', models.JSONField(db_column='content')),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('previous_version_uuid', models.UUIDField(db_column='previous_version_uuid')),
                ('feature_id', models.BigIntegerField()),
                ('tag_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'banners',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterializedView',
        ),
    ]
