# Generated by Django 5.0.4 on 2024-04-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_materializedviewbanners_delete_materializedview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterializedViewBanners',
        ),
    ]
