# Generated by Django 5.0.4 on 2024-04-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_delete_materializedviewbanners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='feature',
            new_name='feature_id',
        ),
    ]
