# Generated by Django 5.0.4 on 2024-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_rename_feature_banner_feature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.IntegerField(blank=True),
        ),
    ]
