# Generated by Django 5.0.4 on 2024-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_alter_banner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
