# Generated by Django 5.0.4 on 2024-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_alter_banner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
