# Generated by Django 5.0.4 on 2024-04-12 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_alter_banner_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
